### ISSUE TITLE
Interface to open the app and the correct view from NFC Tag

### ISSUE THREAD

**Issue by ahlstronomi** [TheRealSense/aalto-app#29]
### Scenario
The user wants to read the NFC tag to get more information about the tool. We need to create a feature that enables this.

### Acceptance criteria
Tapping NFC tag shows the correct tool page.

**Comment by ahlstronomi** [comment]
### Work done
The app now recognises the links.
```
craftio://tools/:id
```
When the application is opened through this kind of link, the Tools component will be opened.

**Ready for review**

**Comment by tripheo0412** [comment]
Works perfectly xD
